version: '2'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-enterprise-kafka:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9101:9101
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://broker:29092,INTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafkaProducerMeasurment:
    image: kafkaproducer-measurement:0.1.0
    build: ./KafkaProducer
    container_name: kafkaProducerMeasurement
    depends_on:
      - broker

  kafkaStreams:
    image: kafkastreams:1.0.0
    build: ./KafkaStreams
    container_name: kafkaStreams
    depends_on:
      - kafkaProducerMeasurment

  rstudio:
    image: rstudio/plumber:0.0.12
    build: .
    container_name: rstudio
    ports:
      - 8787:8787
      - 80:80
    environment:
      USER: user
      PASSWORD: password


